# coding: utf-8

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from clients._generated.petstore.paths.pet.post import AddPet
from clients._generated.petstore.paths.pet_pet_id.delete import DeletePet
from clients._generated.petstore.paths.pet_find_by_status.get import FindPetsByStatus
from clients._generated.petstore.paths.pet_find_by_tags.get import FindPetsByTags
from clients._generated.petstore.paths.pet_pet_id.get import GetPetById
from clients._generated.petstore.paths.pet.put import UpdatePet
from clients._generated.petstore.paths.pet_pet_id.post import UpdatePetWithForm
from clients._generated.petstore.paths.pet_pet_id_upload_image.post import UploadFile


class PetApi(
    AddPet,
    DeletePet,
    FindPetsByStatus,
    FindPetsByTags,
    GetPetById,
    UpdatePet,
    UpdatePetWithForm,
    UploadFile,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
