# coding: utf-8

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from clients._generated.petstore.paths.store_order_order_id.delete import DeleteOrder
from clients._generated.petstore.paths.store_inventory.get import GetInventory
from clients._generated.petstore.paths.store_order_order_id.get import GetOrderById
from clients._generated.petstore.paths.store_order.post import PlaceOrder


class StoreApi(
    DeleteOrder,
    GetInventory,
    GetOrderById,
    PlaceOrder,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
