# coding: utf-8

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from clients._generated.petstore.paths.user.post import CreateUser
from clients._generated.petstore.paths.user_create_with_array.post import CreateUsersWithArrayInput
from clients._generated.petstore.paths.user_create_with_list.post import CreateUsersWithListInput
from clients._generated.petstore.paths.user_username.delete import DeleteUser
from clients._generated.petstore.paths.user_username.get import GetUserByName
from clients._generated.petstore.paths.user_login.get import LoginUser
from clients._generated.petstore.paths.user_logout.get import LogoutUser
from clients._generated.petstore.paths.user_username.put import UpdateUser


class UserApi(
    CreateUser,
    CreateUsersWithArrayInput,
    CreateUsersWithListInput,
    DeleteUser,
    GetUserByName,
    LoginUser,
    LogoutUser,
    UpdateUser,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
