# coding: utf-8

# flake8: noqa

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from clients._generated.petstore.api_client import ApiClient

# import Configuration
from clients._generated.petstore.configuration import Configuration

# import exceptions
from clients._generated.petstore.exceptions import OpenApiException
from clients._generated.petstore.exceptions import ApiAttributeError
from clients._generated.petstore.exceptions import ApiTypeError
from clients._generated.petstore.exceptions import ApiValueError
from clients._generated.petstore.exceptions import ApiKeyError
from clients._generated.petstore.exceptions import ApiException
