# coding: utf-8

# flake8: noqa
"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from clients._generated.petstore.models.api_response import ApiResponse
from clients._generated.petstore.models.category import Category
from clients._generated.petstore.models.inline_object import InlineObject
from clients._generated.petstore.models.inline_object1 import InlineObject1
from clients._generated.petstore.models.order import Order
from clients._generated.petstore.models.pet import Pet
from clients._generated.petstore.models.tag import Tag
from clients._generated.petstore.models.user import User
